player1 = ("Lionel Messi", "Forward", 10, "Captain")
player2 = ("Julian Alvarez", "Striker", 9, "Player")
print("Player 1: ", player1)
print("Name: ", player1[0])
print("Position: ", player1[1])
print("Role: ", player1[3])
team = (player1, player2)
print("\nFirst player: ", team[0][0])
print("Second player number: ", team[1][2])
print("Player 1 details:", player1[1:3])
print("Player 1 details: ")
for i in player1:
    print("-", i)
player1_skils = {"Passing", "Dribbling", "Shooting", "Passing"}
player2_skills = {"Speed", "Shooting", "Passing"}
print("\nPlayer 1 Skills: ", player1_skils)
print("\nPlayer 2 Skills: ", player2_skills)
player1_skils.add("Leadership")
player1_skils.discard("Dribbling")
print("\nUpdated player skill: ", player1_skils)
allskills = player1_skils.union(player2_skills)
commom = player1_skils.intersection(player2_skills)
only_player1 = player1_skils.difference(player2_skills)
difference = player1_skils.symmetric_difference(player1_skils)
print(allskills)
print(commom)
print(only_player1)
print(difference)