student = ("Ahmed Rahman", "Grade 8", "Section A", "Roll 15")
print("Student Details:", student)
print("Name:", student[0])
print("Class:", student[1])
print("Roll Number:", student[-1])
student2 = ("Sara Khan", "Grade 8", "Section B", "Roll 20")
students = (student, student2)
print("\nFirst Student:", students[0][0])
print("Second Student Class:", students[1][1])
print("Student Details:", student[1:3])
print("\nStudent Information:")
for item in student:
    print("-", item)
monday_subjects = {"Math", "English", "Science", "Math"}
tuesday_subjects = {"Science", "Computer", "English"}
print("\nMonday Subjects:", monday_subjects)
print("Tuesday Subjects:", tuesday_subjects)
print("Total Monday Subjects:", len(monday_subjects))
monday_subjects.add("History")
monday_subjects.discard("English")
print("\nUpdated Monday Subjects:", monday_subjects)
all_subjects = monday_subjects.union(tuesday_subjects)
common_subjects = monday_subjects.intersection(tuesday_subjects)
only_monday = monday_subjects.difference(tuesday_subjects)
different_subjects = monday_subjects.symmetric_difference(tuesday_subjects)
print("\nAll Subjects:", all_subjects)
print("Common Subjects:", common_subjects)
print("Only Monday Subjects:", only_monday)
print("Different Subjects:", different_subjects)
